---
stages:
  - stage
  - imageregistry
  - prod
variables:
  GIT_STRATEGY: none

staging:
  stage: stage
  script:
  - cd /opt/miniq-web/miniq-web/
  - git config --global user.name "Hossein Ghorbani"
  - git config --global user.email "h.ghorbani@mobtakerteam.com"
  - git stash
  - git pull origin tmaster
  - cd /opt/miniq-web
  - export DOCKER_CLIENT_TIMEOUT=1200
  - export COMPOSE_HTTP_TIMEOUT=1200
  - docker pull localhub.minimum.money/miniq/miniq-web:latest
  - docker-compose down && docker-compose up -d
  - sleep 5;docker-compose ps
  only:
  - tmaster
  tags: [tmaster]

PushImage:
  stage: imageregistry
  script:
  - docker tag localhub.minimum.money/miniq/miniq-web:latest remotehub.minimum.money/miniq/miniq-web:latest
  - docker push remotehub.minimum.money/miniq/miniq-web:latest
  only:
  - tmaster
  tags: [tmaster]

production:
  stage: prod
  script:
  - cd /opt/miniq-web/miniq-web/
  - git config --global user.name "Hossein Ghorbani"
  - git config --global user.email "h.ghorbani@mobtakerteam.com"
  - export DOCKER_CLIENT_TIMEOUT=300
  - export COMPOSE_HTTP_TIMEOUT=300
  - git stash
  - git pull origin master
  - cd /opt/miniq-web
  - export DOCKER_CLIENT_TIMEOUT=1200
  - export COMPOSE_HTTP_TIMEOUT=1200
  - docker pull remotehub.minimum.money/miniq/miniq-web:latest
  - docker-compose down && docker-compose up -d
  - sleep 5;docker-compose ps
  only:
  - master
  tags: [master]
